name: Package Application with Pyinstaller

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: lol_pishock.py

    - uses: actions/upload-artifact@v2
      with:
        name: lol-pishock
        path: src/dist/windows
